### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by astatine-213** [Rcrwrate/Xdnmb_downer#2]
我检查了一下main.py中第7行得到的“fin”对象，该对象已经不再是一个大字典，而是一个大列表，每一个列表对象是一个对应的字典，这将导致main.py以及run.py无法正常工作
经过手动解析，每一个字典对应的应该是不同的页码，且具体的文章内容位于"replies"键对应的值（一个列表）中所有字典的“content”键下
以下是一个简单的提取所有内容的实例：

（上接main.py第7行）
msg=""
msg+=fin[0]["content"]
for x in fin:
	for y in x['Replies']:
		msg+=y["content"]
with open("temp1.txt","w",encoding="utf-8") as f:
	f.write(msg);f.close()

通过这种方式可以将全文保存到“temp1.txt”，但是伴有html特有的br标记以及部分html元素

**Comment by Rcrwrate** [comment]
> 我检查了一下main.py中第7行得到的“fin”对象，该对象已经不再是一个大字典，而是一个大列表，每一个列表对象是一个对应的字典，这将导致main.py以及run.py无法正常工作 经过手动解析，每一个字典对应的应该是不同的页码，且具体的文章内容位于"replies"键对应的值（一个列表）中所有字典的“content”键下 以下是一个简单的提取所有内容的实例：
> 
> （上接main.py第7行） msg="" msg+=fin[0]["content"] for x in fin: for y in x['Replies']: msg+=y["content"] with open("temp1.txt","w",encoding="utf-8") as f: f.write(msg);f.close()
> 
> 通过这种方式可以将全文保存到“temp1.txt”，但是伴有html特有的br标记以及部分html元素


### 关于从大字典变成大列表的问题

这个是https://github.com/Rcrwrate/Xdnmb_downer/commit/3e1f9ca68a74df047145b08d730c5644a00c2461
这一次提交引发的问题，这次是为了做缓存，修改了中间产物的形式

但实际上我做了适配，适配函数在这里https://github.com/Rcrwrate/Xdnmb_downer/blob/94b4442c926578aa63b186a23f849633962e5d29/Xdnmb.py#L60

但在`get_all()`函数中，我并没有加入适配(我重写了`get_all`，原来的被注释掉了)，可以改用`get_with_cache()`函数解决问题，不需要改动其他代码

### 关于TXT文档导出的问题

我还是倾向直接用epub（笑

TXT导出的部分在这儿
https://github.com/Rcrwrate/Xdnmb_downer/blob/94b4442c926578aa63b186a23f849633962e5d29/Epub.py#L174
你看这无比草率的代码

html标记其实就只有br，x岛的API所致，TXT又不能插入图片，不过有一些阅读器可以读取img的元素标识，例如“阅读”什么的，但我懒得写了（）
